version: 2

registries:
  genos-crates:
    type: cargo-registry
    registry: genos
    url: https://crates.genos.dev/artifactory/api/cargo/crates/index/
    token: "Bearer ${{ secrets.GENOS_REPO_TOKEN }}"

updates:
  - package-ecosystem: cargo
    directory: /
    registries: "*"
    schedule:
      interval: daily

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
